### Lista de Carros
GET http://localhost:5137/api/carros

### Buscar Carro pelo Id
GET http://localhost:5137/api/carros/1

### Cadastrar Carro
POST http://localhost:5137/api/carros
Content-Type: application/json

{
    "name": "Hundai HB20s"
}

### Atualiza os dados do Carro
PUT http://localhost:5137/api/carros/1
Content-Type: application/json

{
    "name": "Honda City"
}


### Remove o Carro pelo Id
DELETE  http://localhost:5137/api/carros/1